export const CLIENT_MOVEMENT_TYPES = {
  VENTA: 'VENTA',
  PAGO: 'PAGO',
  NOTA_CREDITO: 'NOTA_CREDITO',
  AJUSTE: 'AJUSTE',
  SALDO_INICIAL: 'SALDO_INICIAL',
} as const;

export const DEBIT_MOVEMENTS = [
  CLIENT_MOVEMENT_TYPES.VENTA,
  CLIENT_MOVEMENT_TYPES.SALDO_INICIAL,
];

export const CREDIT_MOVEMENTS = [
  CLIENT_MOVEMENT_TYPES.PAGO,
  CLIENT_MOVEMENT_TYPES.NOTA_CREDITO,
];